repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: flake8
      - id: check-merge-conflict
      - id: detect-aws-credentials

  - repo: git://github.com/guykisel/pre-commit-robotframework-tidy
    hooks:
    -   id: robotframework-tidy-wrapper